### PR TITLE
Add python3 wrapper. fixes #5

### LINKED ISSUE #5: #!/usr/bin/env python3 in Alfred does not detect python3 interpreter
It's probably an alfred issue, but on my machine the interpreter was not detected using the /usr/bin/env ,So had to manually use /usr/local/bin/python3 or else the script would output err 127.

I've yet to figure how to configure Alfred to detect other paths, but in terms of portability this is a workflow issue.

### PR DESCRIPTION
**Pull request by avielsh**
Added a python wrapper.
The wrapper check for known paths and selects the latest python3 version found. (configurable)
a py3 file is written inside the script directory after initial setup for faster execution.
On configuration change/error in python,  the script will reinitialize the python3 path.

### CODE REVIEW

**Comment by Acidham** [comment]
Thanks for the wrapper! One suggestion: The py3 file is stored in workflow directory better would be to save this config file locally in `alfred_workflow_data` (https://www.alfredapp.com/help/workflows/script-environment-variables/)

**Comment by avielsh** [comment]
> Thanks for the wrapper! One suggestion: The py3 file is stored in workflow directory better would be to save this config file locally in `alfred_workflow_data` (https://www.alfredapp.com/help/workflows/script-environment-variables/)

Sure , I'll change it when I get near a pc...

P.S I've double checked on default HighSierra and Mojave clean installs and python3 does not reside on /usr/bin so this wrapper is good for smthin..

**Comment by Acidham** [comment]
wrapper is great! I will add it to my other python3 workflows! Looking forward for storing in `alfred_workflow_data` PR ;)

**Comment by Acidham** [comment]
Changed py3 file creation in alfred_workflow_data

**Comment by Acidham** [comment]
https://github.com/Acidham/chromium-hist-bookmarks/releases/tag/v2.1.6

**Comment by avielsh** [comment]
I see you already implemented alfred_workflow_data. Kudus...
But I think you have merged the original pull request 5bf4c47... instead you should merge cad4aef which includes a bunch of bug fixes, code cleanup and comments that were added later on..

**Review by Acidham — COMMENTED** [review]
Not sure why this was not taken

**Comment by avielsh** [comment]
Yep, It looks good now 👏

**Pull request merged**
